CREATE TABLE baanStatus (
  ID SERIAL PRIMARY KEY,
  status INTEGER NOT NULL,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL,
  opmerking VARCHAR(128)
);

CREATE TABLE buttonPresses (
  ID SERIAL PRIMARY KEY,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE score (
    ID INTEGER PRIMARY KEY,
    links INTEGER,
    rechts INTEGER,
    tijd TIMESTAMP WITH TIME ZONE NOT NULL
    );